# ---- Build Stage ----
FROM node:22-alpine AS builder


ARG REACT_APP_BACKEND_URL
ARG REACT_APP_LIST_APPS_PATH
ARG REACT_APP_SUBMIT_URL
ARG REACT_APP_SUBMIT_PATH

# Expose them so CRA inlines them
ENV REACT_APP_BACKEND_URL=${REACT_APP_BACKEND_URL}
ENV REACT_APP_LIST_APPS_PATH=${REACT_APP_LIST_APPS_PATH}
ENV REACT_APP_SUBMIT_URL=${REACT_APP_SUBMIT_URL}
ENV REACT_APP_SUBMIT_PATH=${REACT_APP_SUBMIT_PATH}


WORKDIR /app

# Install dependencies
COPY package.json package-lock.json* ./
RUN npm install

# Copy the rest of the source code
COPY . .

# Build the React app for production
RUN npm install --legacy-peer-deps
RUN npm run build

# ---- Production Stage ----
FROM nginx:alpine

# Copy built assets from builder
COPY --from=builder /app/build /usr/share/nginx/html


EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]