---
apiVersion: v1
kind: Namespace
metadata:
  name: artisanal
---
apiVersion: v1
kind: Secret
metadata:
  name: kettle-ssh-key
  namespace: artisanal
type: Opaque
data:
  ssh_key: "YOUR_BASE64_ENCODED_PRIVATE_KEY_HERE"
---
apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: artisanal
spec:
  ports:
    - port: 6379
      targetPort: 6379
  selector:
    app: redis
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  namespace: artisanal
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
        - name: redis
          image: redis:7-alpine
          ports:
            - containerPort: 6379
---
apiVersion: v1
kind: Service
metadata:
  name: kettle
  namespace: artisanal
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: kettle
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kettle
  namespace: artisanal
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kettle
  template:
    metadata:
      labels:
        app: kettle
    spec:
      containers:
        - name: kettle
          image: adamdocker10/artisanal-kettle:latest
          ports:
            - containerPort: 8080
          env:
            - name: REDIS_HOST
              value: redis
            - name: SSH_USER
              value: kettle
            - name: SSH_KEY
              valueFrom:
                secretKeyRef:
                  name: kettle-ssh-key
                  key: ssh_key
---
apiVersion: v1
kind: Service
metadata:
  name: tea
  namespace: artisanal
spec:
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: tea
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tea
  namespace: artisanal
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tea
  template:
    metadata:
      labels:
        app: tea
    spec:
      containers:
        - name: tea
          image: adamdocker10/artisanal-tea:latest
          ports:
            - containerPort: 80
          env:
            - name: REACT_APP_BACKEND_URL
              value: http://kettle:8080
            - name: REACT_APP_LIST_APPS_PATH
              value: /list/services
            - name: REACT_APP_SUBMIT_PATH
              value: /submit
